package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_09;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/09/day-9-the-best-way-to-test] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"FindBin"},{module=>"Mojo::Base"},{module=>"Mojo::DOM"},{module=>"Mojo::DOM::CSS"},{module=>"Mojo::IOLoop"},{module=>"Mojo::JSON"},{module=>"Mojo::JSON::Pointer"},{module=>"Mojo::Transaction"},{module=>"Mojo::UserAgent"},{module=>"Mojo::UserAgent::Transactor"},{module=>"Mojolicious::Controller"},{module=>"Mojolicious::Plugin::Config"},{module=>"Mojolicious::Plugin::JSONConfig"},{module=>"Test::Mojo"},{module=>"Test::Mojo::Role::Debug"},{module=>"Test::More"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 09)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/09/day-9-the-best-way-to-test> (retrieved on 2018-12-30). Visit the URL for the full contents.

