package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_23;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/23/day-23-one-liners-for-fun-and-profit] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Benchmark"},{module=>"Data::Dumper"},{module=>"Mojo::Autobox"},{module=>"Mojo::ByteStream"},{module=>"Mojo::Collection"},{module=>"Mojo::DOM"},{module=>"Mojo::File"},{module=>"Mojo::JSON"},{module=>"Mojo::Message::Response"},{module=>"Mojo::UserAgent"},{module=>"Mojo::Util"},{module=>"Mojolicious::Command::eval"},{module=>"Mojolicious::Command::get"},{module=>"Mojolicious::Lite"},{module=>"ojo"},{module=>"ojoBox"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 23)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 23)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/23/day-23-one-liners-for-fun-and-profit> (retrieved on 2018-12-30). Visit the URL for the full contents.

