package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_12;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/12/day-12-more-than-a-base-class] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::Base"},{module=>"Moo"},{module=>"MooX::ChainedAttributes"},{module=>"MooX::StrictConstructor"},{module=>"Moose"},{module=>"feature"},{module=>"strict"},{module=>"utf8"},{module=>"warnings"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 12)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 12)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/12/day-12-more-than-a-base-class> (retrieved on 2018-12-30). Visit the URL for the full contents.

