package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_01;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/01/day-1-getting-started] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"App::cpanminus"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 01)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 01)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/01/day-1-getting-started> (retrieved on 2018-12-30). Visit the URL for the full contents.

