package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_14;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/14/day-14-you-promised-to-call] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"GraphQL"},{module=>"Mojo::Promise"},{module=>"Mojo::UserAgent"},{module=>"Mojolicious"},{module=>"Mojolicious::Command::bulkget"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 14)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 14)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/14/day-14-you-promised-to-call> (retrieved on 2018-12-30). Visit the URL for the full contents.

