package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_21;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/21/day-21-virtually-a-lumberjack] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::Asset::File"},{module=>"Mojo::File"},{module=>"Mojo::IOLoop"},{module=>"Mojo::IOLoop::Stream"},{module=>"Mojo::Loader"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 21)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 21)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/21/day-21-virtually-a-lumberjack> (retrieved on 2018-12-30). Visit the URL for the full contents.

