package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_22;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/22/day-22-how-to-build-a-public-rest-api] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"JSON::Validator"},{module=>"Mojolicious::Command::generate::app"},{module=>"Mojolicious::Command::routes"},{module=>"Mojolicious::Plugin::OpenAPI"},{module=>"Mojolicious::Routes::Route"},{module=>"OpenAPI::Client"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 22)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 22)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/22/day-22-how-to-build-a-public-rest-api> (retrieved on 2018-12-30). Visit the URL for the full contents.

