package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_18;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/18/day-18-the-wishlist-model] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"DBI"},{module=>"DBIx::Class"},{module=>"DBM::Deep"},{module=>"Mojo::File"},{module=>"Mojo::Pg"},{module=>"Mojo::SQLite"},{module=>"Mojo::SQLite::Results"},{module=>"Mojo::mysql"},{module=>"Mojolicious"},{module=>"SQL::Abstract"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 18)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/18/day-18-the-wishlist-model> (retrieved on 2018-12-30). Visit the URL for the full contents.

