package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_19;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/19/day-19-make-your-app-installable] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"App::ModuleBuildTiny"},{module=>"App::opan"},{module=>"Dist::Zilla"},{module=>"Dist::Zilla::Plugin::ShareDir"},{module=>"ExtUtils::MakeMaker"},{module=>"File::Share"},{module=>"File::ShareDir"},{module=>"File::ShareDir::Install"},{module=>"Module::Build"},{module=>"Module::Build::Tiny"},{module=>"Mojo::File"},{module=>"Mojo::Home"},{module=>"Mojolicious"},{module=>"Mojolicious::Plugin::Config"},{module=>"Mojolicious::Plugin::InstallablePaths"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 19)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/19/day-19-make-your-app-installable> (retrieved on 2018-12-30). Visit the URL for the full contents.

