package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_13;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/13/day-13-more-about-roles] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Class::Method::Modifiers"},{module=>"List::UtilsBy"},{module=>"Mojo::Base"},{module=>"Mojo::Collection"},{module=>"Mojo::Collection::Role::UtilsBy"},{module=>"Mojo::DOM"},{module=>"Mojo::DOM::Role::PrettyPrinter"},{module=>"Mojo::Log::Role::Clearable"},{module=>"Mojo::Promise"},{module=>"Mojo::UserAgent"},{module=>"Mojolicious"},{module=>"Role::Tiny"},{module=>"Test::Deep"},{module=>"Test::Mojo"},{module=>"Test::Mojo::Role::Debug"},{module=>"Test::Mojo::Role::PSGI"},{module=>"Test::Mojo::Role::Phantom"},{module=>"Test::Mojo::Role::Selenium"},{module=>"Test::Mojo::Role::TestDeep"},{module=>"Test::Mojo::WithRoles"},{module=>"Test::More"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 13)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 13)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/13/day-13-more-about-roles> (retrieved on 2018-12-30). Visit the URL for the full contents.

