package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_24;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/24/day-24-release-and-wrap-up] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojolicious::Plugin::ACME"},{module=>"Wishlist"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 24)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/24/day-24-release-and-wrap-up> (retrieved on 2018-12-30). Visit the URL for the full contents.

