package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_03;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/03/day-3-using-named-routes] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::URL"},{module=>"Mojolicious::Controller"},{module=>"Mojolicious::Plugin::TagHelpers"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 03)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 03)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/03/day-3-using-named-routes> (retrieved on 2018-12-30). Visit the URL for the full contents.

