package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_15;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/15/day-15-start-a-new-yancy-app] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::Pg"},{module=>"Mojo::Pg::Migrations"},{module=>"Mojolicious::Lite"},{module=>"Mojolicious::Plugin::Yancy"},{module=>"Yancy"},{module=>"Yancy::Backend::Dbic"},{module=>"Yancy::Backend::Mysql"},{module=>"Yancy::Backend::Pg"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 15)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 15)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/15/day-15-start-a-new-yancy-app> (retrieved on 2018-12-30). Visit the URL for the full contents.

