package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_06;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/06/day-6-adding-your-own-commands] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Galileo"},{module=>"Minion"},{module=>"Mojo::Pg"},{module=>"Mojo::SQLite"},{module=>"Mojo::mysql"},{module=>"Mojolicious"},{module=>"Mojolicious::Command"},{module=>"Mojolicious::Command::eval"},{module=>"Mojolicious::Command::generate"},{module=>"Mojolicious::Command::nopaste"},{module=>"Mojolicious::Commands"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 06)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 06)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/06/day-6-adding-your-own-commands> (retrieved on 2018-12-30). Visit the URL for the full contents.

