package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_05;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/05/day-5-your-apps-built-in-commands] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"IO::Socket::SSL"},{module=>"Mojo::DOM"},{module=>"Mojo::DOM::CSS"},{module=>"Mojo::JSON"},{module=>"Mojo::Pg"},{module=>"Mojo::UserAgent"},{module=>"Mojolicious::Command::cgi"},{module=>"Mojolicious::Command::cpanify"},{module=>"Mojolicious::Command::daemon"},{module=>"Mojolicious::Command::eval"},{module=>"Mojolicious::Command::generate"},{module=>"Mojolicious::Command::generate::app"},{module=>"Mojolicious::Command::generate::lite_app"},{module=>"Mojolicious::Command::generate::makefile"},{module=>"Mojolicious::Command::generate::plugin"},{module=>"Mojolicious::Command::get"},{module=>"Mojolicious::Command::inflate"},{module=>"Mojolicious::Command::prefork"},{module=>"Mojolicious::Command::psgi"},{module=>"Mojolicious::Command::routes"},{module=>"Mojolicious::Command::test"},{module=>"Mojolicious::Command::version"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 05)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 05)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/05/day-5-your-apps-built-in-commands> (retrieved on 2018-12-30). Visit the URL for the full contents.

