package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_20;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/20/day-20-practical-testing] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"LinkEmbedder"},{module=>"Mock::MonkeyPatch"},{module=>"Mojo::Pg"},{module=>"Mojo::UserAgent"},{module=>"Test::Harness"},{module=>"Test::Mojo"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 20)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/20/day-20-practical-testing> (retrieved on 2018-12-30). Visit the URL for the full contents.

