package Acme::CPANModules::Import::MojoliciousAdvent::2017_12_11;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2017/12/11/day-11-useragent-content-generators] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::DOM"},{module=>"Mojo::Template"},{module=>"Mojo::UserAgent"},{module=>"Mojo::UserAgent::Transactor"},{module=>"Mojo::XMLRPC"},{module=>"XML::Parser"},{module=>"XMLRPC::Fast"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2017 (day 11)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2017 (day 11)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2017/12/11/day-11-useragent-content-generators> (retrieved on 2018-12-30). Visit the URL for the full contents.

